spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
---
spring:
  config:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: create  # (1) 스키마 자동 생성
    show-sql: true      # (2) SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  servlet:
    encoding:
      force-response: true
---
spring:
  config:
    activate:
      on-profile: server
    import: 'aws-parameterstore:'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  # url, username, password 를 aws-parameter store 에서 가져오도록 설정
  #    url: jdbc:mysql://{AWS RDS Endpoint}/test?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
  #    username: {RDS Mysql Admin id}
  #    password: {RDS Mysql Admin password}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#config:
#  domain: {AWS S3 Endpoint}
aws:
  paramstore:
    enabled: true
    prefix: /spring-boot-aws
    name: seb-39-pre-054
    profile-separator: _